apiVersion: v1
kind: Service
metadata:
  name: ai
  namespace: testprep
  labels:
    app: ai
spec:
  type: ClusterIP
  selector:
    app: ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
