apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: testprep
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          resources:
            requests:
              cpu: 800m
              memory: 512Mi
            limits:
              cpu: 1500m
              memory: 1024Mi
          image: ghcr.io/test-prep-ai/backend:1.2.5
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          ports:
            - containerPort: 8080
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: RDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: RDS_USERNAME
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: RDS_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_SECRET_KEY
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: S3_BUCKET_NAME
            - name: SSL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SSL_PASSWORD
