apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: testprep
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
