apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testprep

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-hpa.yaml
  - ai-deployment.yaml
  - ai-service.yaml
  - ai-hpa.yaml
  - ingress.yaml
